/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    `application`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

group = "org.example"
version = "1.0-SNAPSHOT"
description = "learning-java"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
application {
    // Reemplaza con tu FQCN: paquete + nombre de clase con main(...)
    mainClass.set("main.java.MainApplication")
}